"""Initial tables

Revision ID: bdc1df64df83
Revises: 
Create Date: 2026-07-30 11:08:19.668238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdc1df64df83'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('author_name', sa.String(), nullable=False),
    sa.Column('author_date_of_birth', sa.Date(), nullable=True),
    sa.Column('author_citizenship', sa.String(), nullable=True),
    sa.Column('author_biography', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('author_id')
    )
    op.create_index(op.f('ix_authors_author_name'), 'authors', ['author_name'], unique=False)
    op.create_table('series',
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.Column('series_title', sa.String(), nullable=False),
    sa.Column('series_description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('series_id')
    )
    op.create_index(op.f('ix_series_series_title'), 'series', ['series_title'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=False),
    sa.Column('user_email', sa.String(), nullable=False),
    sa.Column('user_hash_password', sa.String(), nullable=False),
    sa.Column('user_about', sa.String(), nullable=True),
    sa.Column('user_register_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_user_email'), 'users', ['user_email'], unique=True)
    op.create_index(op.f('ix_users_user_name'), 'users', ['user_name'], unique=True)
    op.create_table('books',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('book_title', sa.String(), nullable=False),
    sa.Column('book_description', sa.String(), nullable=True),
    sa.Column('book_year', sa.Integer(), nullable=False),
    sa.Column('book_isbn', sa.String(), nullable=False),
    sa.Column('book_original_language', sa.String(), nullable=False),
    sa.Column('book_series_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_series_id'], ['series.series_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('book_id')
    )
    op.create_index(op.f('ix_books_book_isbn'), 'books', ['book_isbn'], unique=True)
    op.create_index(op.f('ix_books_book_title'), 'books', ['book_title'], unique=False)
    op.create_table('book_authors',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['authors.author_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['book_id'], ['books.book_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('book_id', 'author_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book_authors')
    op.drop_index(op.f('ix_books_book_title'), table_name='books')
    op.drop_index(op.f('ix_books_book_isbn'), table_name='books')
    op.drop_table('books')
    op.drop_index(op.f('ix_users_user_name'), table_name='users')
    op.drop_index(op.f('ix_users_user_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_series_series_title'), table_name='series')
    op.drop_table('series')
    op.drop_index(op.f('ix_authors_author_name'), table_name='authors')
    op.drop_table('authors')
    # ### end Alembic commands ###
